services:
  admin-panel:
    build: .
    ports:
      - '${PORT:-4000}:${PORT:-4000}'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env
    environment:
      - PORT=${PORT:-4000}
